Fix Clang unused-but-set-variable warning
generated by gemini CLI.

Failure message:
packages/services/Car/cpp/evs/apps/default/src/TexWrapper.cpp:112:11: error: variable 'format' set but not used [-Werror,-Wunused-but-set-variable]
  112 |     GLint format;
      |           ^

Test: presubmit
Bug: 429520052
Flag: EXEMPT, warning fixup
Change-Id: I993e74335d0f8a0b8a0a822c273dfecd95a9e591